{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relay.fullname" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
data:
  relay.yaml: |
    {{- .Values.config | nindent 4 }}
{{- end }}
